# Generated by Django 3.0.5 on 2020-04-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='text',
            field=models.TextField(max_length=20, null=True),
        ),
    ]
